controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - jointGripper
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home
  - group: gripper
    pose: open